### ISSUE TITLE
Why can't I return different error types in a "andThen" chain?

### ISSUE THREAD

**Issue by kolandar** [supermacro/neverthrow#30] opened 2020-05-04 23:42 UTC
Hi,

Thank you for publishing this!

I wanted to get started right away but ran into a seemingly trivial problem I am too much of a noob to solve. Any help would be appreciated!

The compiler complains when I want to compose multiple results with the .andThen() method

```
type E1 = 'invalid'
type E2 = 'also invalid'
type E3 = 'invalid again'
type Errors = E1 | E2 | E3

const f1 = (sth: unknown) => Result<string, E1>
const f2 = (input: string) => Result<string, E2>
const f3 = (thing: string) => Result<string, E3>

const result: Result<string, Errors> = f1('test')
                         .andThen(f2)
                         .andThen(f3)
```

The compiler complains that that the result of f1 is not assignable to the result of f2, specifically Result<string, E1> is not assignable to Result<string, E2>.

I thought that the mismatch of results and function parameters wouldn’t hurt, because .andThen() doesn’t even call the next function if the result is of type Err. Any idea how I could help with the type inference?

**Comment by greptail** [comment] 2020-05-05 22:40
Hey @kolandar,

So I copy / pasted your code to try and run it and noticed a few things. 

Firstly, `Result` is only a type - it does not have a corresponding runtime class (in typescript a class is both a value and a type). 

Hence an expression such as:

```typescript
const f1 = (sth: unknown) => Result<string, E1>
```

is not valid. `Result<string, E1>` says, "I represent a `string` or a `E1`".

What I think you were trying to do is this:

```typescript
const f1 = (sth: unknown) => ok(sth)
```

So if I replace your `f2` and `f3` functions with the same pattern, then what I get is:

```typescript
const f1 = (sth: unknown) => ok(sth) // this function returns Result<unknown, {}>
const f2 = (input: string) => ok(input) // this function returns Result<string, {}>
const f3 = (thing: string) => ok(thing) // this function returns Result<string, {}>
```

> **Segue**: all the results have a `{}` error type because the compiler at this point has insufficient information to infer what the error type is. Explicitly annotating your values would resolve this.

Now I'm at:

```typescript
const result: Result<string, Errors> = f1('test')
  .andThen(f2) // <== compiler error here
  .andThen(f3)
```

And I get a compiler error:

```
[typescript]
Argument of type '(input: string) => Ok<string, {}>' is not assignable to parameter of type '(t: unknown) => Result<string, {}>'.
  Types of parameters 'input' and 't' are incompatible.
    Type 'unknown' is not assignable to type 'string'.
```

So what's going on?

Well, recall that `f1('test')` returns a `Result<unknown, {}>`.

So calling `.andThen` on `Result<unknown, {}>` means that the function passed to `andThen` must adhere to the following interface:

```typescript
<U>(data: unknown) => Result<U, {}>
```

Where `U` can be anything, but the error value is already determined ahead of time. It must be the same type of the current `Result`.

So the issue is that `f2` doesn't adhere to the interface defined above. Namely, the argument to `f2` is a string, but typescript expects it to be `unknown`.

Hope that helps! 

Also, please close this issue if this answers your question / you don't have any follow up questions!

**Comment by kolandar** [comment] 2020-05-06 19:59
@supermacro 
thank you very much for the thorough explanation!

Did I understand correctly that andThen can't be be used to map a Result<T,E> to a Result<U,F>?

So the following will never work at compile-time, although the compiled code works perfectly fine?

(BTW: Sorry, I should have made it clear that my snippet was pseudo...very bad and ambiguous pseudo I guess...)
```ts
import {Result, ok, err} from 'neverthrow';

type E1 = {err: 'invalid'};
type E2 = {err: 'unacceptable'};
type E3 = {err: 'totally off'};

type Errors = E1 | E2 | E3

type F1 = (sth: unknown) => Result<string, E1>;
type F2 = (sth2: string) => Result<string, E2>;
type F3 = (sth3: string) => Result<string, E3>;

const f1: F1 = (sth: unknown) => {
    console.log(sth);
    const x = Math.random() * 10;
    return (x > 5) ? ok('yes-one') : err({err: 'invalid'});
}

const f2: F2 = (sth: string) => {
    console.log(sth);
    const x = Math.random() * 10;
    return (x > 5) ? ok('yes-two') : err({err: 'unacceptable'});
}

const f3: F3 = (sth: string) => {
    console.log(sth);
    const x = Math.random() * 10;
    return (x > 5) ? ok('yes-three') : err({err: 'totally off'});
}

const result: Result<string, Errors> = f1('maybe').andThen(f2).andThen(f3)
```
Maybe I am a little slow here, but I thought `.andThen()` was meant to chain synchronous functions returning `Result` types, correct? 

Would be grateful for hints! THX!

**Comment by supermacro** [comment] 2020-05-07 17:14
Hey @kolandar,

I see what you mean. 

> Did I understand correctly that andThen can't be be used to map a Result<T,E> to a Result<U,F>?

That is correct. `neverthrow` is built in such a way that it short circuits upon encountering a `Err` instance.

What are the implications of this? Let me demonstrate via a code sample

```typescript
const r1 = 

```

**Comment by paduc** [comment] 2020-05-13 13:04
I hope you don't mind me jumping in this discussion.

I see how having a union Error type can solve the issue but I'm not sure it's the only solution.

We could also have ```andThen``` return an error of type of the union of possible errors in the chain.

Example:
```typescript
// Let's say we have the following functions
const validateUserObject: (user: User) => Result<User, InvalidUsernameError>
const insertUserToDb: (user: User) => Result<User, DbError | UsernameTakenError>

const res = validateUserObject(user).andThen(insertUserToDb)
// We could have
typeof res = Result<User, InvalidUsernameError | DbError | UsernameTakenError>

// This way, we can handle the specific errors
if(res.isErr()){
   if(res.error instanceOf InvalidUsernameError || res.error instanceOf UsernameTakenError){
      res.send({error: "Please choose another username"})
   }
   else {
      // We know it's a DbError
      res.send({error: "Service unavailable, please try again."});
   }
}
```

The only change necessary would be to change the signature of ```andThen``` to
```typescript
// In Ok<T, E> or Err<T,E>
andThen<U, F>(_f: (t: T) => Result<U, F>): Result<U, E | F>
```
The implementation itself doesn't need to change and the change would be non-breaking because ```E | E === E```, meaning that if you have code that chained multiple ```Result``` with the same error type, the union would be of that error type. It wouldn't interfere with the short-circuiting of the function in ```Err```.

I see this capability as interesting when working with an external module that returns a ```Result<T, ModuleSpecificError>```. It's error type is not necessarily compatible with my local error type (maybe the error is in a ```message``` property while my local errors use an ```err``` property).

**Comment by supermacro** [comment] 2020-05-17 15:16
I've thought about addressing this issue by creating a union type that would allow for returning different error types just as @paduc has demonstrated. But in my opinion I do not think the benefit is there.

For example, say you have the following types:

```typescript
interface DbError {
  code: number
  message: string
}

interface ValidationError<T> {
  data: T
  errors: string[]
}

type OtherError = string

const myResult: Result<number, DbError | ValidationError<User> | OtheError>
```

Now let's suppose that we're dealing with the error:

```typescript
if (myResult.isErr()) {
  const myError= myResult.error
}
```

`myError` now contains that union type above (`DbError | ValidationError<User> | OtheError`) ... The question is now, how do you distinguish between each of these types?

You have to do additional checks. Which ultimately do not save the developer any time or convenience. 

Hence I still believe that by having one single error type `E` you end up with a better experience.

Further, I would argue that by enforcing that the user leverages discriminated unions and type guards as I showed in my comment above, that you end up with more idiomatic typescript code.

**Comment by paduc** [comment] 2020-05-20 09:36
> `myError` now contains that union type above (`DbError | ValidationError<User> | OtheError`) ... The question is now, how do you distinguish between each of these types?

In my case, the error types are all classes so I can easily distinguish between them using `instanceof`.

If you really want to use interfaces and types, I guess the easiest solution would be adding a string literal to each type.

```typescript
interface DbError {
  type: 'DbError'
  code: number
  message: string
}

interface ValidationError<T> {
  type: 'ValidationError'
  data: T
  errors: string[]
}

const myResult: Result<number, DbError | ValidationError<User>>

if(myResult.isErr()){
  if(myResult.type === 'DbError'){
    //...
  }
  else{
    // compiler knows its a ValidationError
  }
} 

```

> 
> You have to do additional checks. Which ultimately do not save the developer any time or convenience.
> 

When you are handling a chain of tasks, it can fail at any step. Maybe you will handle all failures the same way (ex: returning the text message contained in `e.message`.

However, I often want to handle the failure case in a different manner depending on the type of error (ex: In case of a validation error, send the message to the user. In case of a database error, report it to the admin and retry).  
To achieve this, there is no avoiding additional checks and it requires something to discriminate between error types. It's not a matter of saving time or convenience.

Yes, I could use a single error type `E`, add a `type` string literal to it like in my example above, and discriminate using the `type` property. But I think it is idiomatic typescript to define different types for this purpose.

Furthermore, my chain includes a call to an external module that returns a `Result` with a specific error type. I have no control over that error type, so I can't make it implement my generic `E` type. I have to deal with it and this results in code that looks pretty contrived to me:

This example is a bit contrived but displays the manoeuver necessary to force the module specific error into my project specific error type:
```typescript
import validateUser from 'external-module'
// assuming validateUser(user: any): Result<boolean, ValidationError>

// Using the current api

ok<unknown, Error>(myUser)
  .andThen(user =>
    // I need to convert ValidationError to Error type using mapErr
    validateUser(user).mapErr(
      (e: ValidationError) => new Error('ValidationError: ' + e.reason),
    ),
  )
  .map(user => user.name)
  .match(
    username => {
      console.log('Created user ' + username)
    },
    e => {
      if (e.message.startsWith('ValidationError')) {
        // Ok, send back validation errors to the user
        res.send({ error: e.message })
      }
      else{
        // Bad, log this error
        logger.error("Error in the user creation process")
        // Return a generic error to the user, we don't want them to see system errors
        res.send({ error: "System error, please try again later."})
      }
    },
  )


// Using an api returning a union type

ok<unknown, Error>(myUser)
  .andThen(validateUser)
  .map(user => user.name)
  .match(
    username => {
      console.log('Created user ' + username)
    },
    e => {
      // e is Error | ValidationError
      if (e instanceof ValidationError) {
        // Ok, send back validation errors to the user
        res.send({ error: e.reason })
      }
      else{
        // Bad, log this error
        // e is Error
        logger.error("Error in the user creation process", e.message)
        // Return a generic error to the user, we don't want them to see system errors
        res.send({ error: "System error, please try again later."})
      }
    },
  )

```

**Comment by paduc** [comment] 2020-05-29 09:31
@supermacro Have you had a chance to read my message above ?

It's kinda blocking for me as I'm preparing to do a big refacto of a pretty big project to use `neverthrow` everywhere. I don't want to have to do another big one down the line. :)

**Comment by supermacro** [comment] 2020-05-29 12:36
Hey @paduc,

My apologies for the late response, I haven't had much time to focus on issue grooming recently.

> Yes, I could use a single error type E, add a type string literal to it like in my example above, and discriminate using the type property. But I think it is idiomatic typescript to define different types for this purpose.

I respectfully disagree. I personally am a big advocate for using [discriminated unions](https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions) in situations such as this one.

I think there is, however, some room for improvement because of the boilerplate currently required to "align" distinct types with each other.

Example:

```typescript
const getUserFromDb = (userId: number): Promise<Result<User, DbError>> => { ... }
const validateUser = (user: User): Result<never, ValidationError> => { ... }

type RouteError = { type: 'db_error'; error: DbError } | { type: 'validation_error'; error: ValidationError }

const getValidUser = async (userId: number): Promise<Result<User, RouteError>> => {
  const result = await getUserFromDb(userId)

  return result
    .mapErr(e => ({ type: 'db_error', error: e }))
    .andThen(user =>
      validateUser(user).mapErr(e => ({ type: 'validation_error', error: e }))
    )
}
```

Is it annoying? Yes. Is it unusual that a statically typed language requires this sort of type-gymnastics? No (at least with my experience with Haskell, Elm, and Rust to a lesser extent).

I would be open to having a utility function in `neverthrow` that generalizes the creation of a `{type : 'string_literal'; value: E}` for a given `E` ... if it is even possible to do given the nature of string literal types in typescript. 

--- 

> I see this as a benefit and can't see the cost.

Typescript does not merge duplicate types. i.e. given `E | E`, the compiler is not smart enough to merge the duplicate types into one.

Because the compiler isn't smart enough to merge duplicate types, I can already foresee how a type error that tells users that a value must be `{ name: string } | { name: string } | { name: string }` is going to be harmful for users. Now imagine that instead of a type `{ name: string }` your have something a lot more complex like in a real-life scenario.

Secondly, I have some reservation around changing to this new API because it deviates from the implied specification of the `Either` / `Result` type that languages like Rust, Scala, and Elm define. I don't know of a single `Either` / `Result` whose `andThen` equivalent allows for varying error types. This to me signals that there's a good reason not to do this (although I do not know right now what that reason is). I'm sure there is a Functor law, or something similar, that this might violate and could lead to some subtle but serious problems for users. 

---

> Furthermore, if my chain includes a call to an external module that returns a Result with a specific error type, I have no control over that error type, so I can't make it implement my generic E type. I have to deal with it and this results in code that could look better.

Your code example confused me a bit because the second part of the example has access to the `ValidationError` class. If you do have access to the `ValidationError` class, then in your first part, where you have to call `mapErr` you can create a discriminated union like I demonstrate above in my own example. 

But let's suppose that this `external-module` package doesn't expose the `ValidationError`. I would recommend that you implement a wrapper for the `validateUser` function such that you implement a error type that is suitable / appropriate for your situation / application.

```typescript
const validateUser = (user: unknown): Result<boolean, MyOwnValidationError> =>
  externalModule.validateUser(user).mapErr(intoMyOwnValiationError)
```

It's almost always likely that `Result`s returned by external modules don't adhere to your applications conventions anyways, so explicitly mapping over the error values in order to have a consistent error convention in your system is beneficial.

--- 

Everything I've mentioned here is my opinion. I don't want to come off as arrogant, and I am still open to discuss improvements / solutions. But I also want to ensure that there is good merit and justification to any features that are implemented for this library. So I will always be respectfully critical of proposals to make sure they objectively make sense!

**Comment by paduc** [comment] 2020-05-29 13:59
> Typescript does not merge duplicate types. i.e. given `E | E`, the compiler is not smart enough to merge the duplicate types into one.

Yes, it's not smart enough to merge type shapes like `{name: string}` but it's smart enough to merge unions of declared types. So if you have defined an error type `E` and all your chained methods return a  `Result<*,E>`, then the resulting union type would be `E` (and not `E | E | E | ...`).

My point is that people who want to use a single error type would see no change in having `andThen` with the following signature:
```typescript
andThen<U>(_f: (t: T) => Result<U, F>): Result<U, E | F>
```

My goal is to be able to know exactly which error types can come up at the end of my chain, just be looking at the type of the `Result`. If I use an app-wide discriminated union type `E`, then I only know that my error is of type `E`. Maybe it can only be 2 variants of `E` maybe it can be any other number. I don't want to handle error type cases which cannot happen. I don't want to miss any error type case that can happen.

With the signature above, the compiler gives me a precise list of all error types at the end of my chain.

If one of the chained methods returns a new type of error, it's error type signature will change and the compiler will warn me that I need to handle this new case at the end of my chain.
 
> 

> Secondly, I have some reservation around changing to this new API because it deviates from the implied specification of the `Either` / `Result` type that languages like Rust, Scala, and Elm define. I don't know of a single `Either` / `Result` whose `andThen` equivalent allows for varying error types. This to me signals that there's a good reason not to do this (although I do not know right now what that reason is). I'm sure there is a Functor law, or something similar, that this might violate and could lead to some subtle but serious problems for users.

I took personal interest in `neverthrow` because of it's pragmatic approach. I tried many other `Either` / `Result` type packages but they all compromise on usability for the sake of being "pure" or whatever. Maybe they're right, I'm not sure.
What I believe is that if there happens to be subtle but serious problems to an implementation, they can be dealt with when they occur.

I don't want to impose my opinions either and would love to avoid the pitfalls my intuitions might lead me into. But I just don't see them. I guess I'll try refactoring my app using a fork with `andThen` returning unions of error types and see where that takes me.

**Comment by supermacro** [comment] 2020-05-30 19:00
> but it's smart enough to merge unions of declared types. So if you have defined an error type E and all your chained methods return a Result<*,E>, then the resulting union type would be E (and not E | E | E | ...).

I don't quite follow. I would need to see a code example to see how this would work in practice.

---

Going back to one of your past comments:

> Yes, I could use a single error type E, add a type string literal to it like in my example above, and discriminate using the type property.

I still stand by this approach. Which is what I use when merging various error types in a long chain or results.

**Comment by realpha** [comment] 2020-06-19 10:36
Hi there, 
I've been following this discussion for quite a while now from the sidelines and I do understand @supermacro 's reservations (to some extend)

> Going back to one of your past comments:

> >Yes, I could use a single error type E, add a type string literal to it like in my example above, and discriminate using the type property.

> I still stand by this approach. Which is what I use when merging various error types in a long chain or results

This is definetely an idioamtic approach in most circumstances, and you are right that `andThen` or `bind` or however the equivalent is called in other languages doesn't allow a different error type to be returned (AFAIK). 

BUT this approach comes with a cost (and is also sometimes criticized in the respective communities): composability on the macro level can only be achieved by sacrifizing type expressiveness at the mirco level.
@supermacro has demonstrated this in one of his previous examples pretty well. Compare:
(modified from the OP)
```typescript
type E1 = number
type E2 = string
interface E3 {
  errorCode: number
  message: string
}

type MyUnion = E1 | E2 | E3

type F1 = (sth: unknown) => Result<string, E1>;
type F2 = (sth2: string) => Result<string, E2>;
type F3 = (sth3: string) => Result<string, E3>;

//...Implementation

const result: Result<string, MyUnion> = f1('maybe').andThen(f2).andThen(f3)
```
with the proposed solution:
```typescript
type F1 = (sth: unknown) => Result<string, MyUnion>;
type F2 = (sth2: string) => Result<string, MyUnion>;
type F3 = (sth3: string) => Result<string, MyUnion>;

//...Implementation

const result: Result<string, MyUnion> = f1('maybe').andThen(f2).andThen(f3)
```
I left out the dicrimininator but I think my argument still stands:
**In order to compose arbitrary functions returning `Result` types, one has to alter or overload their signatures. Thus reducing the expressiveness of the signature.**

Additionally it is not possible to centrally handle `Result` types at the moment, because the error types of a given pipeline never line up.

I was drawn to this GREAT library, because it allows me to be expressive with error paths. At the same time, the possibility to easily compose different functions without them having to know the context in which they are composed would be a really BIG WIN. Especially, since the propsed changes by @paduc are minimal and non-breaking, I would be in favour of changing the interface.

**Comment by paduc** [comment] 2020-12-09 16:46
For you information, I've been using a workaround to be able to compose `Result` and `ResultAsync` with different error types. 

I've been using it in production for several months and it works flawlessly for me. The solution is pretty simple.

I created a `neverthrow.d.ts` file in my repo and added it to the `typeRoots` section of my `tsconfig.json`.

`neverthrow.d.ts` contains the same type declarations you would find in `node_modules/neverthrow/dist/index.d.ts` with these simple changes:

```typescript
class Ok<T, E> {
    // ...
    andThen<U, F>(f: (t: T) => Result<U, F>): Result<U, E | F>
    asyncAndThen<U, F>(f: (t: T) => ResultAsync<U, F>): ResultAsync<U, E | F>
    // ...
  }
  class Err<T, E> {
    // ...
    andThen<U, F>(f: (t: T) => Result<U, F>): Result<U, E | F>
    asyncAndThen<U, F>(f: (t: T) => ResultAsync<U, F>): ResultAsync<U, E | F>
    // ...
  }

  class ResultAsync<T, E> implements PromiseLike<Result<T, E>> {
    // ...
    andThen<U, F>(f: (t: T) => Result<U, F> | ResultAsync<U, F>): ResultAsync<U, E | F>
    // ...
  }
```

This allows me to achieve the following behaviour:

```typescript
const resA = ok<null, E1>(null);
const resB = ok<null, E2>(null);

const res = resA.andThen(() => resB);
// res is Result<null, E1 | E2>
// this would result in a compile error normally
```

It's a "hack" but it works for me and might for others.

**Comment by supermacro** [comment] 2020-12-16 18:44
Hey @paduc, I had an idea recently where `neverthrow` could automatically generate this info for a user. 

It would be a little cli tool that would update the types using this snippet you made above. 

That way, users can decide for themselves which types for `andThen` they want. 

What do you think?

**Comment by paduc** [comment] 2020-12-17 08:51
Hi @supermacro ! 

I would definitely welcome a cleaner alternative to my "hack" (it's a one-time thing though).

A cli-tool seems a fair bit of work. I have seen npm packages that provide "alternate" modes for their libs and maybe `neverthrow` could do the same.

Something like:
```typescript
import { ResultAsync } from 'neverthrow/unionErrors`

**Comment by toby-wollit** [comment] 2021-01-21 16:29
This in an interesting discussion, we are facing the same issue.
We would like to union our errors rather than wrapping them.

```typescript
type DbError  = { type: 'DbErrorX', type: 'DbErrorY' }
findByUserId(userId: string): ResultAsync<User, DbError>

type ServiceError = DbError | ( { type: 'ServiceErrorX', type: 'ServiceErrorY' })
findUserAndDoSomethingUseful(userId: string): ResultAsync<User, ServiceError> {
    return findByUserId(userId)
        .andThen(user => err({ type: 'ServiceErrorX' }))
}
```

This approach saves us having to wrap DbError's as ServiceError's but it means the we have to add lots of `.mapErr(e => e as ServiceError)` calls or specify return types to stop the compiler moaning.`

**Comment by paduc** [comment] 2021-01-21 16:43
@toby-wollit Have you tried my "hack" above ? If yes, does it break anything else in your projet ?

**Comment by toby-wollit** [comment] 2021-01-21 16:46
@paduc is does work yes but I don't like the idea of keeping the type definitions in sync!

It would be great if we could find a solution to this issue that satisfied everyone :)

**Comment by supermacro** [comment] 2021-01-25 15:02
Alright folks .. After 8 months of thinking through this, I think I am finally persuaded to go down the route of joining types.

I'm planning on doing some work soonish on this. Maybe I'll get around to it this week.

I realized that because Rust and Haskell and basically all the other well-known languages that have a `Result` don't have subtyping. So it's literally impossible to do `T | A` .. it's just not part of those languages. But in typescript, this is allowed!

**Comment by paduc** [comment] 2021-01-25 15:08
Hurray ! Tell me if I can be of any help !

**Comment by supermacro** [comment] 2021-01-26 17:25
Alrighty, I have published a new version behind a `beta` tag for now.

```
> npm install neverthrow@beta
```

Release notes: 

https://github.com/supermacro/neverthrow/releases/tag/v4.1.0-beta.0

----

I am closing this issue, but feel free to open a new issue regarding this topic!

**Closed by supermacro** 2021-01-26 17:25 UTC
