### ISSUE TITLE
Errors type inferring

### ISSUE THREAD

**Issue by flodlc** [supermacro/neverthrow#419] opened 2022-09-29 13:35 UTC
Type inferring doesn't seem to work for `okAsync` and `errAsync`.

In this case, I expect to have something like `ResultAsync<null, Error1 | Error2>` as a returned type for `testAsync`.
Is this the expected behavior ?

For the sync version (`test`), it works as expected.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/3781663/193044448-b9619658-91de-4973-90f1-0c510b076276.png">

**Comment by supermacro** [comment] 2022-10-16 18:17
### Please reproduce with structurally different values

Note that TS is structurally typed - meaning that equivalence of type is based on the **structure**, not the **names**, of types. 

In other words; `Error1` and `Error2` are structurally equivalent at the moment, and what you **_may_** (I don't know this for sure - it's a hypothesis) be seeing is actually TS doing some optimization and removing a needless / duplicate type. 

But one thing is certain - `Error1` and `Error2` are certainly identical from the point of view of TypeScript. 

[here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUylAggZwJ4DsDGcAvnAGZQQhwDkuyAbqjABYUDu1AUN-gDYCGmTHACiaaAEYUADxjJcAE2FiKURJzhwwUYPX5y4mSshbBcAcwBccXAFcQAI1TdN5kwGVjpiwAoAlNZ2jqjqmppQJrZQuHCmmAB0RiAmzGbmGsScRDwCQqLiUABMMnKKygWhWjp6BhAsqAAqqRbWmDA6FnAucG4wnsne5v6t7WmV4ZHRsakJdcyNzema2dk8ELhtschtWHiEALxw-nD7AHyVwKRHALL6zPFQ-IqUx+fxAKx+43ARMFExqAwOAIPjobHyqgk-j8GVWEz+U0BuxBYIh0EK0KynCAA) is an example where the errors are NOT structurally the same, and I see that the behavior is consistent with what we would expect of `neverthrow`.

Here is a screenshot for convenience:

![image](https://user-images.githubusercontent.com/10621548/196051273-ef9b6642-ada9-437d-aa85-7bdf7b2015a1.png)

### `andThen` API behaves as expected with structurally different values

Just to drive the point home further, I also double checked that `andThen` is also inferring correctly, and it looks to be correct:

![image](https://user-images.githubusercontent.com/10621548/196051388-a7101a26-17d5-473c-8541-3bf47fd3c69d.png)


### Action Items

Please either:

- Close the issue if this is satisfactory, or
- Create a reproducible case that uses structurally distinct types

Also, thank you for your patience :slightly_smiling_face:  ... I know I took a while to respond to this!

**Comment by supermacro** [comment] 2022-10-19 13:06
Closing this as there's been no activity since I posted my above message - feel free to re-open or create a new issue.

**Closed by supermacro** 2022-10-19 13:06 UTC
