### ISSUE TITLE
Add `Promise<Result<...>>` as valid return for `x` in  `asyncAndThen(x)`

### ISSUE THREAD

**Issue by nidomiro** [supermacro/neverthrow#240] opened 2021-02-18 10:31 UTC
I currently have the problem that I cannot use an async function for `asyncAndThen`.

```typescript
...
.asyncAndThen(async (value): Promise<Result<MyDto, GenericError<MyErrorEnum>>>  => {
			...
		})
```

gives me the error:
```
TS2345: Argument of type '(value: MySourceDto) => Promise<Result<MyDto, GenericError<MyErrorEnum, unknown>>>' is not assignable to parameter of type '(t: MySourceDto) => ResultAsync<MyDto, GenericError<MyErrorEnum, unknown>>'.   Type 'Promise<Result<MyDto, GenericError<MyErrorEnum, unknown>>>' is missing the following properties from type 'ResultAsync<MyDto, GenericError<MyErrorEnum, unknown>>': _promise, map, mapErr, andThen, and 3 more.
```

.

A Possible solution could be changing the signature of `asyncAndThen`.
Current:
```typescript
asyncAndThen<U, F>(f: (t: T) => ResultAsync<U, F>): ResultAsync<U, E | F>;
```
New:
```typescript
asyncAndThen<U, F>(f: (t: T) => ResultAsync<U, F> | Promise<Result<U,F>>): ResultAsync<U, E | F>;
```

**Comment by paduc** [comment] 2021-02-18 12:51
Hi @nidomiro, `asyncAndThen` is a method to chain a `Result` with a method that returns a `ResultAsync`, not with an asynchronous method.

If you want it to work out, you may change your chained method so it returns a `ResultAsync` instead of a `Promise<Result>`. If you are dealing with async code, `ResultAsync.fromPromise` will probably be of help to obtain a proper `ResultAsync`.

**Comment by nidomiro** [comment] 2021-02-18 13:13
Hi @paduc,

thanks for your answer.

When I'm using async-await the Result of that **always** is a Promise. Therefore I cannot return a `AsyncResult<...>` but only a `Promise<Result<...>>`.

What I'm using `asyncAndThen` for is something like this:
```typescript
function a() {
	return someActionThatRetunsAResult()
		.asyncAndThen(async (value): Promise<Result<MyDto, GenericError<MyErrorEnum>>> => {
			const result = await updateDBEntryWithData(value);
		...
			if (result == null) {
				return err(...);
			} else {
				return ok(value);
			}
		});
}
```

My current workaround solves the Problem but is not ideal:
```typescript
function toAsyncResult<TValueBefore, TValueAfter, TError>(
	f: (value: TValueBefore) => Promise<Result<TValueAfter, TError>>,
): (value: TValueBefore) => ResultAsync<TValueAfter, TError> {
	return (value) => new ResultAsync(f(value));
}



function a() {
	return someActionThatRetunsAResult()
		.asyncAndThen(
			toAsyncResult(
				async (value): Promise<Result<MyDto, GenericError<MyErrorEnum>>> => {
					const result = await updateDBEntryWithData(value);
					...
					if (result == null) {
						return err(...);
					} else {
						return ok(value);
					}
				}),
		);
}
```

**Comment by paduc** [comment] 2021-02-18 14:11
@nidomiro when using `ResultAsync` you unfortunately have to stop using `async/await` (which use `Promise`).  

For your own async methods, try to return a `ResultAsync`.

For third-party methods that return a `Promise`, wrap it using `ResultAsync.fromPromise`. 
The first argument is a promise and the second is a method to handle the error case of the promise (which should be handled because we don't want to throw...).

If `updateDBEntryWithData` is an internal method, I would refactor it to return a `ResultAsync`. 
But let's say `updateDBEntryWithData` is a third-party method that you cannot alter. Your example could look a bit like this:

```ts
function a() {
  return someActionThatRetunsAResult()
    // Step 1: wrap your native promise
    .asyncAndThen((value) => ResultAsync.fromPromise(updateDBEntryWithData(value), (e) => {
      // what should happen if updateDBEntryWithData throws ?
      return new SomeError(e.message) // for you to chose
    }))
    // Step 2: transform into error if null
    .andThen((valueOrNull) => valueOrNull === null ? err(new SomeOtherError()) : ok(valueOrNull))
}
```

**Comment by supermacro** [comment] 2021-02-19 03:39
`Promise<Result>>` is incongruous with `neverthrow` by design.

Besides the recommendation that paduc already made, you can do what I personally like to do, which is create named functions that conform to the `neverthrow` interface. 

So instead of having inline anonymous `async` functions inside of `asyncAndThen`, my recommendation would be to create a named function:

```typescript
const descriptiveName = (value): ResultAsync<MyDto, GenericError<MyErrorEnum>> => ResultAsync.fromPromise(updateDBEntryWithData(value), (e) => { /* error handling*/ })
  .andThen((dbResult) => dbResult === null ? err(...) : ok(dbResult))
```

Here's an example from a side project of mine:

[source](https://github.com/parlez-vous/server/blob/master/src/routes/embed/add-comment.ts)

```typescript
export const handler = route<LeafComment>((req, _) => {
  const data = {
    ...req.params,
    ...req.body,
  }

  return decode(dataDecoder, data).map(({ postId, ...rawComment }) =>
    createComment(postId, rawComment).map(intoLeaf).map(AppData.init)
  )
})
```

**Comment by nidomiro** [comment] 2021-02-22 07:12
Thanks for your answers :)

I think now I understand your point now. You want to guarantee that there are absolutely no exceptions thrown when using neverthrow.

While I'm absolutly into using neverthrow instead of exceptions there are some points where an exception must go on (eg. out of memory).

Maybe I have to use my workaround as the default.

**Comment by supermacro** [comment] 2021-02-22 15:28
> While I'm absolutly into using neverthrow instead of exceptions there are some points where an exception must go on (eg. out of memory).

Yup, there are definitely cases when `neverthrow` does not make sense. 

The distinction is between recoverable and irrecoverable errors (such as being out of memory as you mentioned).

`neverthrow` is specifically for dealing with recoverable errors (where your program **should** continue to run, and where a developer **should** consider an error ahead of time).

For irrecoverable errors, I stop running my program (but there could be other mechanisms you could use). For example, when I run web servers, I **expect** a certain set of environment variables to be defined. If one or many of those env variables are not present, then I shut down the server.

Rust docs have some good documentation on the distinction between recoverable and irrecoveable errors: 

https://doc.rust-lang.org/stable/book/ch09-03-to-panic-or-not-to-panic.html

---

Closing this issue, but feel free to open a new issue in the future.

**Closed by supermacro** 2021-02-22 15:28 UTC
Labels: question
