### ISSUE TITLE
Option

### ISSUE THREAD

**Issue by pawndev** [supermacro/neverthrow#71] opened 2020-06-30 16:18 UTC
Hey guys,

Have you planned to implement the `Option` type/class ?

**Comment by supermacro** [comment] 2020-06-30 19:10
Hey @pawndev,

I have no plans in implementing an `Option` / `Maybe` type.

Can you provide more information / context, as well as some examples of how you see `Option` being used in this package?

**Comment by pawndev** [comment] 2020-06-30 19:42
Hey @supermacro 

I had no plan initially, I was just looking at your existing implemented methods, and thinking about the `ok` and `err` methods in rust, that return an Option ( https://doc.rust-lang.org/std/result/enum.Result.html#method.ok  https://doc.rust-lang.org/std/result/enum.Result.html#method.err )

It was just for my curiosity 😄

**Comment by supermacro** [comment] 2020-06-30 19:51
Ahh, I see what you mean. Although `neverthrow` draws **significant** inspiration from Rust's `Result` type, there are no plans to incorporate a method that returns an `Option` right now.

I will close this issue by the end of the week if you have no more comments / questions.

**Comment by pawndev** [comment] 2020-06-30 19:54
I have no more comments. Thanks for your reply, and thanks for `neverthrow` 🙂 
Have a great day !

**Closed** 2020-06-30 21:36 UTC

**Comment by paduc** [comment] 2020-07-01 07:58
Hey @pawndev, out of curiosity myself, have you found a use for an `Option` type in typescript ?
I tried using a library that had one but found it to be too cumbersome. I rather use `type Option<T> = T | undefined` now.

**Comment by pawndev** [comment] 2020-07-01 08:21
Hey @paduc 
Nop, didn't find some real use case for `Option` in typescript, I thinked about it because the Option type could have the same api as the Result type.
And, with an api like this, we could write with the same syntax, less error handling etc..

But I'm agree with you when you said `found it to be too cumbersome` 😄

**Comment by paduc** [comment] 2020-07-01 09:22
@pawndev I have a bunch of methods that return `Option` types, like `findUserById(id: string) => Option<User>` and a helper might be useful to chain this type of methods in a `Result` chain.

I'm thinking of a helper that would handle the `Nothing` case of the `Option` as an `Error`.

```typescript
const result: Result<User, UserNotFoundError> = Result.fromOption(findUserById(userId), () => new UserNotFoundError(userId);
```

**Comment by pawndev** [comment] 2020-07-01 13:46
@paduc That's a great use case in fact. Actually my methods  return directly a Result<User, UserNotFound>
But indeed, I have some other methods that return just a T or null ( my Nullable/Option type). And a `fromOption` could be worth.

**Comment by paduc** [comment] 2020-07-01 13:52
@supermacro I have a couple ideas for helpers (for instance, to transform an array of `Result` into a `Result`, a bit like `Promise.all`). Do you think `neverthrow` could include such helpers or would they belong elsewhere ?

**Comment by supermacro** [comment] 2020-07-02 19:42
The idea of an `Option` is tempting to me, although I would define it in terms of two classes:

```
type Option<T> = Some<T> | None
```

where `Some<T>` and `None` are ES6 classes (same design pattern as with `Result` - my rationale being that you can then have useful methods such as:

- `Option<T>.unwrap() => T | null`
- `Option<T>.map<U>((val: T) => U) => Option<U>`
- etc, etc

---

In terms of having utility methods such as converting a `Result<T, E>[]` into a  single`Result`, I am not sure. The use case might be too narrow, and it's a few lines of code to implement on your own outside of `neverthrow`.

**Comment by chestercharles** [comment] 2021-04-09 00:30
@supermacro are you still considering adding an `Option` to `neverthrow`? 

Introducing `Result` has been a game changer for some of our teams in terms of enabling them to write JavaScript in a more pure, functional style without too much overhead. The only thing we are missing is an `Option` to so we can "never null" as well as "never throw" 😉 . 

It looks like there might be a few libraries out there we could use, but I'd far prefer using one with a similar implementation and API to `neverthrow`.  If it is something you are still considering, I would be interested in contributing, too.

**Comment by supermacro** [comment] 2021-04-09 14:06
Hey @chestercharles,

Out of curiosity, do your teams take advantage of `strictNullChecks` compiler flag?

Some info:

- https://www.tsmean.com/articles/learn-typescript/strict-null-checks-best-practice/
- https://www.typescriptlang.org/tsconfig#strictNullChecks

With strict null checks, you can have union types that specify whether something is null:

```
type MaybeNumber = number | null
```

Not having `strictNullChecks` would defeat the purpose of an `Option` type anyways since anything can be null or undefined at that point!

What has your experience been with the above suggestion? 

The only thing I see lacking from having unions like this is that you don't have the same level of expressivity compared to having a `Option` type that you can `.map` over and do things with in a chain.

**Comment by chestercharles** [comment] 2021-04-12 16:43
Most of our projects use `strict` mode, and I've used union types in the way you talking about for things like this:
```
type User = { name: string};
const getUserById: (id: number) => User | null = /* ... */;
const user = getUserById(1);
if (user) {
  // do things 
}
```
Having strict null checks and null-unioned types does help ensure the correctness of my program - the compiler forces me to check for the user before operating on it.

But what I really like about Option is that I can be more expressive (as you mentioned) and less imperative with control flow:
```
const maybeDoThings = pipe(getUserById, Option.fromNullable, Option.map(doThings))
```
Some libraries like [`fp-ts`](https://github.com/gcanti/fp-ts) provide a `fromPredicate` method to do things like this:
```
type Order = { status: 'pending' | 'complete'}
const processOrder: (o: Order) => Order = /* ... */;
const isOrderPending: (o: Option) => boolean = /* ... */
const processPendingOrders = pipe(Option.fromPredicate(isOrderPending), Option.map(processOrder))
```
I suppose that Option is really just syntactic sugar for `if(user) { /* do this */}` but just like Result, I believe that thinking in terms of these abstractions helps a developer write a simpler program.

**Comment by supermacro** [comment] 2021-04-21 14:34
Hey @chestercharles sorry for the delayed response. 

I've been putting some thought into this. But I'm still not sure that this is something that should necessarily be added to `neverthrow`.

My assumption is that there are plenty of options (haha) out there for you to chose from. For example `fp-ts`'s [implementation of `Option`](https://gcanti.github.io/fp-ts/modules/Option.ts.html).

Thus, your team could have a utility function `intoOption` like this:

```typescript
export const intoOption = <T, E>(result: Result<T, E>): Option<T> =>
  result.match(
    (val) => Option.some(val),
    () => Option.none
  )
```

Note that the above is currently only implemented for `Result` but one could easily overload this to work for `ResultAsync` as well.

**Comment by supermacro** [comment] 2021-04-21 14:37
Using `Option`s with `neverthrow` is, in my opinion, just a matter of using a pattern such as the above to use whichever Option implementation a user may want. 

Now, if the problem is that current Option implementations aren't "good" for whatever reason. Then that's something I'm open to discussing - but realistically that would still live in its own repo / npm lib.
